version: "3.8"

services:
  mlops-api:
    build: .
    container_name: mlops
    ports:
      - "8000:8000"     # FastAPI 포트
    volumes:
      - .:/app          # model.pkl 변경 시 즉시 반영
    restart: always

